/* =========================================================
   LINUM CORE — I18N copy (PT + EN)
   ========================================================= */

const COPY = {
  pt: {
    nav: {
      home: "Home",
      competencies: "Serviços",
      portfolio: "Soluções",
      ceo: "Sobre",
      feedbacks: "Vozes",
      contact: "Contato",
      cta: "Falar conosco",
    },
    hero: {
      eyebrow: "Est. 2024 · São Paulo · Brasil",
      title_a: "Reconectando o que",
      title_b: "nunca deveria",
      title_c: "ter sido desconectado.",
      lede: "Desenvolvemos soluções digitais completas com propósito. Unimos design, código e estratégia para criar sistemas que geram impacto real.",
      cta_primary: "Falar com especialista",
      cta_secondary: "Ver o trabalho",
      meta_a: "Disponível para novos projetos",
      meta_b: "Atendimento global",
      scroll: "Role para baixo",
      categories: [
        { label: "Desenvolvimento", kind: "compass" },
        { label: "Design", kind: "quill" },
        { label: "Segurança", kind: "key" },
        { label: "Estratégia", kind: "lens" },
      ],
      stats: [
        { num: "12+", label: "Sistemas em produção" },
        { num: "100%", label: "Entrega no prazo" },
        { num: "5 anos", label: "Cliente médio" },
      ],
    },
    manifesto: {
      eyebrow: "Manifesto · I",
      tokens: [
        { t: "Não construímos" },
        { t: "apenas sistemas," },
        { t: "mas sim" },
        { t: "a" },
        { t: "linha invisível", c: "accent" },
        { t: "que existe antes" },
        { t: "do código" },
        { t: "e que realiza" },
        { t: "as verdadeiras" },
        { t: "conexões.", c: "accent" },
      ],
      attrib: "Gabriel Gomes · Fundador",
    },
    comp: {
      num: "II",
      title: <>O que <em>fazemos</em></>,
      lede: "Disciplinas que praticamos com seriedade. Cada uma servindo à mesma intenção: restaurar a conexão entre intenção e resultado.",
      items: [
        { num: "01", title: "Engenharia de sistemas sob medida", body: "Web, mobile e backend construídos do zero. Arquitetura sólida, código limpo, performance e segurança como pré-requisitos — não como features.", tags: ["Next.js", "Node", "React Native", "Postgres"] },
        { num: "02", title: "Consultoria técnica", body: "Diagnóstico de stacks legadas, decisões de arquitetura, code review e mentoria de times.", tags: ["Discovery", "Architecture", "Mentoring"] },
        { num: "03", title: "Manutenção evolutiva", body: "Cuidamos do que já existe. Refatoração disciplinada e débito técnico tratado com método.", tags: ["Refactor", "SRE", "Observability"] },
        { num: "04", title: "Integrações & APIs", body: "Conectamos o que parecia incompatível. Plataformas, serviços e fluxos de dados com contratos claros e resiliência.", tags: ["REST", "gRPC", "Webhooks", "Kafka"] },
        { num: "05", title: "Produto & UX", body: "Quando faz sentido, ajudamos a desenhar o produto. Wireframes, fluxos, design system.", tags: ["Discovery", "UI/UX", "Design System"] },
        { num: "06", title: "Cloud, DevOps & segurança", body: "Infraestrutura como código, CI/CD, monitoramento e hardening. Operação previsível, custo controlado, deploys sem teatro.", tags: ["AWS", "GCP", "Terraform", "Kubernetes"] },
      ],
    },
    portfolio: {
      num: "III",
      title: <>Trabalhos <em>recentes</em></>,
      lede: "Uma seleção de projetos entregues. Cada um pensado como uma costura específica — não há solução pronta repetida.",
      filters: ["Todos", "Concluídos", "Em curso", "Open Source"],
      featured_label: "Em destaque · 2026",
      featured: {
        title: "Atelier Vésper",
        desc: "Plataforma de gestão para um ateliê de alta-costura francês. Estoque de tecidos, encomendas sob medida, gestão de provas e financeiro reunidos em uma única costura de dados — substituindo cinco planilhas e dois sistemas legados.",
        tags: ["Next.js 15", "tRPC", "Prisma", "Postgres", "Stripe"],
        status: "done",
        year: "2026",
        hue: "navy",
        links: [["Live", "↗"], ["Case study", "↗"]],
      },
      items: [
        { title: "Nodo Health", year: "2025", desc: "Prontuário eletrônico para uma rede de clínicas integrativas. Foco em fluxo do profissional e privacidade do paciente.", tags: ["React Native", "FHIR", "AWS"], status: "done", links: [["Case", "↗"]], hue: "wine" },
        { title: "Trama API", year: "2025", desc: "Orquestração entre ERPs legados e canais de venda modernos. Idempotência, retries e auditoria ponta a ponta.", tags: ["Node", "Kafka", "K8s"], status: "wip", links: [["Docs", "↗"]], hue: "neutral" },
        { title: "Ofício Studio", year: "2024", desc: "Site institucional e CMS para um estúdio de arquitetura. Editorial, denso, lento — como deveria ser.", tags: ["Astro", "Sanity"], status: "done", links: [["Live", "↗"]], hue: "navy" },
        { title: "Linum CLI", year: "2025", desc: "Ferramenta interna para scaffolding e auditoria de projetos. Open source, escrita em Rust.", tags: ["Rust", "OSS"], status: "wip", links: [["GitHub", "↗"]], hue: "wine" },
        { title: "Coral Atlas", year: "2024", desc: "Visualização de dados ambientais para uma ONG marinha. Mapas, séries temporais, narrativas guiadas.", tags: ["D3", "MapboxGL"], status: "done", links: [["Live", "↗"], ["Case", "↗"]], hue: "neutral" },
      ],
    },
    ceo: {
      num: "IV",
      title: <>O <em>fundador</em></>,
      lede: "Linum Core começou com uma pessoa. Continua tendo uma pessoa no centro de cada decisão.",
      name: "Gabriel Gomes",
      role: "Fundador · Engenheiro principal",
      portrait: ["Retrato", "do fundador"],
      portrait_caption: "GG · 2026",
      portrait_corner: "01 / 01",
      bio: [
        "Engenheiro de software há mais de uma década, com passagem por bancos, startups de saúde e estúdios de produto. Acredita que <em>código é prosa</em> — e que prosa boa começa em ouvir bem.",
        "Linum Core nasceu da frustração com soluções genéricas vendidas para problemas únicos. Aqui cada cliente é tratado como um caso só seu — porque é.",
      ],
      skills_title: "Mapa de competências",
      skills_tabs: ["Técnicas", "Stacks", "Relacionais"],
      skill_sets: {
        "Técnicas": [
          { label: "Arquitetura", value: 0.92 }, { label: "Performance", value: 0.85 },
          { label: "Segurança", value: 0.78 }, { label: "Testes", value: 0.88 },
          { label: "DX", value: 0.9 }, { label: "Observabilidade", value: 0.72 },
        ],
        "Stacks": [
          { label: "TypeScript", value: 0.95 }, { label: "Node.js", value: 0.9 },
          { label: "React", value: 0.92 }, { label: "Rust", value: 0.65 },
          { label: "Postgres", value: 0.85 }, { label: "AWS · GCP", value: 0.78 },
        ],
        "Relacionais": [
          { label: "Escuta", value: 0.95 }, { label: "Diagnóstico", value: 0.9 },
          { label: "Liderança", value: 0.82 }, { label: "Mentoria", value: 0.85 },
          { label: "Escrita", value: 0.88 }, { label: "Apresentação", value: 0.8 },
        ],
      },
    },
    fb: {
      num: "V",
      title: <>O que <em>permanece</em></>,
      lede: "Clientes contam o que ficou depois do projeto entregue.",
      items: [
        { quote: "Resolveram em três meses o que dois fornecedores anteriores não conseguiram em dois anos. E ainda nos ensinaram a manter.", person: "Marina Tavares", role: "CTO · Atelier Vésper", initials: "MT" },
        { quote: "Senti que o Gabriel entendeu a clínica antes de escrever uma linha de código. O sistema parece feito por dentro de nós.", person: "Dr. Henrique Lopes", role: "Diretor médico · Nodo Health", initials: "HL" },
        { quote: "Documentação impecável, decisões justificadas por escrito, prazos cumpridos. Trabalho de adulto, raro no mercado.", person: "Sofia Bertoletti", role: "Head de Engenharia · Trama", initials: "SB" },
      ],
    },
    contact: {
      num: "VI",
      title_a: "Vamos",
      title_b: "costurar",
      title_c: "alguma coisa?",
      lede: "Conte o problema. Em até 48 horas você recebe um diagnóstico inicial — gratuito, por escrito, sem proposta empurrada.",
      cta: "Enviar briefing",
      channels: [
        { label: "Email", value: "ggvgabriel05@gmail.com", href: "mailto:ggvgabriel05@gmail.com" },
        { label: "WhatsApp", value: "+55 11 99000-0000", href: "#" },
        { label: "LinkedIn", value: "in/gabriel-linum", href: "#" },
        { label: "GitHub", value: "github.com/linumcore", href: "#" },
        { label: "Instagram", value: "@linumcore", href: "#" },
      ],
    },
    footer: {
      tagline: "Tecnologia que conecta essências.",
      cols: [
        { title: "Site", items: ["Home", "Competências", "Portfólio", "Fundador", "Vozes", "Contato"] },
        { title: "Contato", items: ["ggvgabriel05@gmail.com", "+55 11 99000-0000", "São Paulo · BR"] },
        { title: "Social", items: ["LinkedIn", "GitHub", "Instagram"] },
      ],
      copyright: "© 2026 Linum Core · Todos os direitos reservados",
      colophon: "Playfair Display · Inter · JetBrains Mono",
    },
  },

  en: {
    nav: {
      home: "Home",
      competencies: "Services",
      portfolio: "Solutions",
      ceo: "About",
      feedbacks: "Voices",
      contact: "Contact",
      cta: "Talk to us",
    },
    hero: {
      eyebrow: "Est. 2024 · São Paulo · Brazil",
      title_a: "Reconnecting what",
      title_b: "should never",
      title_c: "have been disconnected.",
      lede: "We craft complete digital solutions with purpose. Design, code and strategy stitched together into systems that make real impact.",
      cta_primary: "Talk to a specialist",
      cta_secondary: "See the work",
      meta_a: "Available for new projects",
      meta_b: "Global delivery",
      scroll: "Scroll",
      categories: [
        { label: "Development", kind: "compass" },
        { label: "Design", kind: "quill" },
        { label: "Security", kind: "key" },
        { label: "Strategy", kind: "lens" },
      ],
      stats: [
        { num: "12+", label: "Systems in production" },
        { num: "100%", label: "On-time delivery" },
        { num: "5 yrs", label: "Average client" },
      ],
    },
    manifesto: {
      eyebrow: "Manifesto · I",
      tokens: [
        { t: "We do not build" },
        { t: "just systems," },
        { t: "but the" },
        { t: "invisible thread", c: "accent" },
        { t: "that exists before" },
        { t: "the code," },
        { t: "the one that makes" },
        { t: "the true" },
        { t: "connections.", c: "accent" },
      ],
      attrib: "Gabriel Gomes · Founder",
    },
    comp: {
      num: "II",
      title: <>What we <em>practice</em></>,
      lede: "Disciplines we practice with care. Each serving the same intent: restore the connection between purpose and outcome.",
      items: [
        { num: "01", title: "Bespoke systems engineering", body: "Web, mobile and backend built from scratch. Sound architecture, clean code, performance and security as prerequisites — not features.", tags: ["Next.js", "Node", "React Native", "Postgres"] },
        { num: "02", title: "Technical consulting", body: "Legacy stack diagnosis, architecture decisions, code review and team mentoring.", tags: ["Discovery", "Architecture", "Mentoring"] },
        { num: "03", title: "Living maintenance", body: "We tend to what exists. Disciplined refactoring, technical debt handled with method.", tags: ["Refactor", "SRE", "Observability"] },
        { num: "04", title: "Integrations & APIs", body: "We connect what seemed incompatible. Platforms, services and data flows with clear contracts and resilience.", tags: ["REST", "gRPC", "Webhooks", "Kafka"] },
        { num: "05", title: "Product & UX", body: "When it fits, we help shape the product. Wireframes, flows, design system.", tags: ["Discovery", "UI/UX", "Design System"] },
        { num: "06", title: "Cloud, DevOps & security", body: "Infrastructure as code, CI/CD, monitoring and hardening. Predictable operation, controlled cost, deploys without theatre.", tags: ["AWS", "GCP", "Terraform", "Kubernetes"] },
      ],
    },
    portfolio: {
      num: "III",
      title: <>Recent <em>work</em></>,
      lede: "A selection of shipped projects. Each one stitched specifically — no recycled solutions.",
      filters: ["All", "Shipped", "In progress", "Open source"],
      featured_label: "Featured · 2026",
      featured: {
        title: "Atelier Vésper",
        desc: "Operations platform for a French haute-couture atelier. Fabric inventory, bespoke orders, fitting sessions and finance stitched into a single fabric of data — replacing five spreadsheets and two legacy systems.",
        tags: ["Next.js 15", "tRPC", "Prisma", "Postgres", "Stripe"],
        status: "done",
        year: "2026",
        hue: "navy",
        links: [["Live", "↗"], ["Case study", "↗"]],
      },
      items: [
        { title: "Nodo Health", year: "2025", desc: "Electronic medical records for a network of integrative clinics. Focused on practitioner flow and patient privacy.", tags: ["React Native", "FHIR", "AWS"], status: "done", links: [["Case", "↗"]], hue: "wine" },
        { title: "Trama API", year: "2025", desc: "Orchestration between legacy ERPs and modern sales channels. Idempotency, retries, end-to-end audit.", tags: ["Node", "Kafka", "K8s"], status: "wip", links: [["Docs", "↗"]], hue: "neutral" },
        { title: "Ofício Studio", year: "2024", desc: "Institutional site and CMS for an architecture studio. Editorial, dense, slow — as it should be.", tags: ["Astro", "Sanity"], status: "done", links: [["Live", "↗"]], hue: "navy" },
        { title: "Linum CLI", year: "2025", desc: "Internal tooling for project scaffolding and auditing. Open source, written in Rust.", tags: ["Rust", "OSS"], status: "wip", links: [["GitHub", "↗"]], hue: "wine" },
        { title: "Coral Atlas", year: "2024", desc: "Environmental data visualisation for a marine NGO. Maps, time series, guided narratives.", tags: ["D3", "MapboxGL"], status: "done", links: [["Live", "↗"], ["Case", "↗"]], hue: "neutral" },
      ],
    },
    ceo: {
      num: "IV",
      title: <>The <em>founder</em></>,
      lede: "Linum Core began with one person. It still has one person at the centre of every decision.",
      name: "Gabriel Gomes",
      role: "Founder · Principal engineer",
      portrait: ["Founder", "portrait"],
      portrait_caption: "GG · 2026",
      portrait_corner: "01 / 01",
      bio: [
        "Software engineer for over a decade, having passed through banks, health startups and product studios. Believes that <em>code is prose</em> — and that good prose begins with listening well.",
        "Linum Core was born from a frustration with generic solutions sold for singular problems. Here each client is treated as a case of their own — because they are.",
      ],
      skills_title: "Skill map",
      skills_tabs: ["Technical", "Stack", "Relational"],
      skill_sets: {
        "Technical": [
          { label: "Architecture", value: 0.92 }, { label: "Performance", value: 0.85 },
          { label: "Security", value: 0.78 }, { label: "Testing", value: 0.88 },
          { label: "DX", value: 0.9 }, { label: "Observability", value: 0.72 },
        ],
        "Stack": [
          { label: "TypeScript", value: 0.95 }, { label: "Node.js", value: 0.9 },
          { label: "React", value: 0.92 }, { label: "Rust", value: 0.65 },
          { label: "Postgres", value: 0.85 }, { label: "AWS · GCP", value: 0.78 },
        ],
        "Relational": [
          { label: "Listening", value: 0.95 }, { label: "Diagnosis", value: 0.9 },
          { label: "Leadership", value: 0.82 }, { label: "Mentorship", value: 0.85 },
          { label: "Writing", value: 0.88 }, { label: "Presenting", value: 0.8 },
        ],
      },
    },
    fb: {
      num: "V",
      title: <>What <em>remains</em></>,
      lede: "What clients say stayed with them after the work was delivered.",
      items: [
        { quote: "They solved in three months what two previous vendors could not in two years. And taught us how to keep it.", person: "Marina Tavares", role: "CTO · Atelier Vésper", initials: "MT" },
        { quote: "I felt Gabriel understood the clinic before writing a single line of code. The system feels made from within us.", person: "Dr. Henrique Lopes", role: "Medical director · Nodo Health", initials: "HL" },
        { quote: "Impeccable documentation, decisions justified in writing, deadlines met. Grown-up work, rare in the market.", person: "Sofia Bertoletti", role: "Head of Engineering · Trama", initials: "SB" },
      ],
    },
    contact: {
      num: "VI",
      title_a: "Shall we",
      title_b: "stitch",
      title_c: "something?",
      lede: "Tell us the problem. Within 48 hours you receive a written first diagnosis — free, no pushed proposal.",
      cta: "Send a brief",
      channels: [
        { label: "Email", value: "ggvgabriel05@gmail.com", href: "mailto:ggvgabriel05@gmail.com" },
        { label: "WhatsApp", value: "+55 11 99000-0000", href: "#" },
        { label: "LinkedIn", value: "in/gabriel-linum", href: "#" },
        { label: "GitHub", value: "github.com/linumcore", href: "#" },
        { label: "Instagram", value: "@linumcore", href: "#" },
      ],
    },
    footer: {
      tagline: "Technology that connects essences.",
      cols: [
        { title: "Site", items: ["Home", "Practice", "Work", "Founder", "Voices", "Contact"] },
        { title: "Contact", items: ["ggvgabriel05@gmail.com", "+55 11 99000-0000", "São Paulo · BR"] },
        { title: "Social", items: ["LinkedIn", "GitHub", "Instagram"] },
      ],
      copyright: "© 2026 Linum Core · All rights reserved",
      colophon: "Playfair Display · Inter · JetBrains Mono",
    },
  },
};

window.COPY = COPY;
